# services:
#     backend:
#         build:
#             context: .
#         environment:
#             - BUILD_TARGET=linux
#         ports:
#             - "8000:8000"
#         volumes:
#             - .:/app
#         restart: unless-stopped

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app
        working_dir: /app
        command: uv run uvicorn main:app --host 0.0.0.0 --port 8000

    frontend:
        build:
            context: ./flutter_frontend
            dockerfile: Dockerfile
        environment:
            - BUILD_TARGET=linux
        volumes:
            - ./flutter_frontend/build:/app/build
        working_dir: /app

